language: go

go:
  - "1.10.2"

env:
  global:
    - LINUX_BINARY_PATH: ${GOPATH}/bin/terraform-provider-rollbar
    - DARWIN_BINARY_PATH: ${GOPATH}/bin/darwin_amd64/terraform-provider-rollbar

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
  - make vet
  - make test

# Build and zip the binaries.
before_deploy:
  - GIT_TAG=$(git describe --tags)
  - make build
  - mv ${LINUX_BINARY_PATH} ${LINUX_BINARY_PATH}_v${GIT_TAG}
  - zip -j ${LINUX_BINARY_PATH}_v${GIT_TAG}_linux_amd64.zip ${LINUX_BINARY_PATH}_v${GIT_TAG}
  - make build-darwin
  - mv ${DARWIN_BINARY_PATH} ${DARWIN_BINARY_PATH}_v${GIT_TAG}
  - zip -j ${DARWIN_BINARY_PATH}_v${GIT_TAG}_darwin_amd64.zip ${DARWIN_BINARY_PATH}_v${GIT_TAG}

deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file:
    - ${LINUX_BINARY_PATH}_v${GIT_TAG}_linux_amd64.zip
    - ${DARWIN_BINARY_PATH}_v${GIT_TAG}_darwin_amd64.zip
  skip_cleanup: true
  file_glob: "true"
  on:
    # branch: "master"
    tags: true
