version: "3"
services:
  go:
    build: .
    volumes:
      - .:/project
    environment:
      - CGO_ENABLED=0
    command:
      - /bin/bash
      - -e
      - -c
      - |
          cd /project
          go test ./rollbar/ -v
